name: Build & Deploy to Firebase
on:
  push:
    branches:
    - master
jobs:
  build:
    name: Build The Vue App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout & Install Dependencies
        uses: action/checkout@master
        uses: action/setup-node@master
        run: npm install
        run: npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
  deploy:
    name: Deploy To Firebase
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: action/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - name: Deploy To Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: "profile-f26401004"